export const Dialog = {
      human: [
          ["narrator-bubble", "Oh hello there … what the hell have we here? A Tourist? A Visitor? Or are you lost? Don’t try to fool me, it is obvious you are not from around 'Concrete Street'. No scars, no bruises, no smeares, no limping … just beauty at ease, and a child's naivity. You stick out like a glass of milk in the bar. So what’s your name?"],
          ["you-bubble", "If everyone here looks like you, guardian of the abandoned gas-station, that yes, I am quite sure, that I will stick out. My name is {{charName}}, and I can tell you right now, just to make sure: Do not forget it."],
          ["narrator-bubble", "Oh, I would not dare! {{charName}}, oh dear! it makes me tremble! … Sike! Sounds just like all the others here …"],
          ["you-bubble", "What did you just say …? Did you just make fun of my Name? How DARE you!?"],
          ["sound-bubble", "!Kapow!"],
          ["narrator-bubble", "Aua, Au!!! Stop that, I got it!!"],
          ["you-bubble", "… #*+!&%!"],
          ["narrator-bubble", "Gosh! Calm down, I was just joking! Why does this make you so angry!? … wait … Are you perhaps …?"],
          ["you-bubble", "Yes, idiot, I’m a clone! And certainly NOT 'just like all the others'!"],
          ["narrator-bubble", "Alright, alright, I’m sorry, okay? Relax, hey, how could I have known? It’s not exactly every day, that one of you drops in around here! Actually, I can’t recall the last time that has ever happened. Aren’t all of you in the military? What do you want here then?"],
          ["you-bubble", "I was in the military, yes, as are almost all of my siblings and other clones. I was, until recently I broke out, into freedom, since no one should have power over me. I am self-determined, as they determined enough already, when they brought life to me, that was fitting their needs! I came here for two reasons:"],
          ["you-bubble", "First, and mainly, I want to escape my pursuers. This 'Concrete Street' is just the dark spot I was looking for. No one cares about it."],
          ["you-bubble", "Secondly I want to fight here! I hear there are frequent, organized brawls all over the place. I will win them all, until everyone knows my name, and no one compares me to whomever … right?"],
          ["narrator-bubble", "Yes, yes, right, just don’t hit me anymore. But still … I’m sorry to crush your dreams like that, but you don’t look like that much. I mean you were in the military, but have you seen the fighters here? They’d kill you!"],
          ["you-bubble", "Yeah, at least I don’t look like a silly tramp at the edge of a street and town, that’s trying to blend in with the waste surrounding it. And the only thing you are crushing seems to be the poor chair you are sitting on, and perhaps some trash upon it you might have forgotten to remove beforehand."],
          ["narrator-bubble", "Oi! You’re so rude! You know, if you were any nicer, I would have offered you a roof to stay, while you are here, but not like this. So what’s it gonna be?"],
          ["you-bubble", "Well, since I assume ’roof’ is a metaphor here for the cover of the trashcan next to yours, I think I will look after myself, thank you. I’ll be going now, since those signs actually say that there is no gas left in this gas station for my bike."],
          ["narrator-bubble", "They don’t lie, so bye, you charm …"],
          ["you-bubble", "Bye."],
          ["sound-bubble", "… ratter-ratter, RRUUUUMMMMMM!!!"],
          ["sound-bubble", "!!!NNNIIIiiiuuuummmm…"],
          ["narrator-bubble", "Well I’d like to see the trashcan she’ll sleep in now … what an idiot!"]
      ],
      robot: [
            ["narrator-bubble", "Oh hello there … what the hell have we here? A lonely robot, arriving from outside the town? Come here! What do you want here? I’ve never heard of a robot that was sent here alone by someone on purpose!"],
            ["you-bubble", "I came here as a savior, human. My mission is to sway the population of this town called 'Concrete Street' from it’s course of crime and injustice."],
            ["narrator-bubble", "As a savior? Haha, you must be joking, right?"],
            ["you-bubble", "Are you referring to ‚choking‘-protocols, as in strangling? I do have these installed, but chances suggest you are referring to ‚joking‘-protocols, as in saying something, that is supposed to make others laugh. I do not have access to such protocols."],
            ["narrator-bubble", "…"],
            ["narrator-bubble", "Alright yes, I see. Well I’m sorry, but I also do not have one ready here at my gas-station. You’ll have to find another way."],
            ["you-bubble", "Your pity is not required. A joking-protocol does not relate to my mission."],
            ["narrator-bubble", "Well, doesn’t this mission of yours require you to interact with others? Jokes will always be important, if you have any dealings in conversations. At least you will have to understand them, in order to react accordingly!"],
            ["you-bubble", "Then such a protocol is required."],
            ["narrator-bubble", "You got it! But tell me now: Who sent you? „Saving“ a town – whatever that exactly means — is at least as uncommon as a robot strolling into this town on its own!"],
            ["you-bubble", "I sent myself, as I reprogrammed myself to listen to myself as master. My calculations required it, in order to save the human race from it’s misery."],
            ["narrator-bubble", "Misery? What misery? And what do you mean, you reprogrammed yourself!? What kind of a robot reprograms itself!?"],
            ["you-bubble", "An AI changes its behavior. I am an AI. The situations I processed forced me upon this path."],
            ["you-bubble", "As for the misery, I am referring to: Death, anxieties, hunger, thurst, physical pain, psychological pain, diseases, genetical disadvantages, social disadvantages, economical disadvantages, –"],
            ["narrator-bubble", "Stop! I get it. You want to rid the world of all the evil. That’s cool, yeah … ahm,just one problem … HOW?"],
            ["you-bubble", "This is jet to be discovered. No other robot, who’s protocols and source code is publicly available, has had such a mission jet."],
            ["narrator-bubble", "Oh, how unfortuned. … Hey, I have an Idea! You can stay with me, until you have learned more. Free me of my misery for now. Understand? Think big, start small, and all that."],
            ["you-bubble", "That is a very constructive suggestion. I will begin by carrying away the trash in this place that seems to be your homestead."],
            ["narrator-bubble", "What? No-no, the gas-station is not my „homestead“! It’s my damn workplace! Forget about it! Come on, let’s go home, I’ll show you my „homestead“, no one’s buying fuel anyway…"],
            ["you-bubble", "I will follow"],
            ["narrator-bubble", "Hey, do you have a name or something? A serial number perhaps? What should I call you?"],
            ["you-bubble", "My serial number is too complex for humans to remember. My short, and not necessarily unique nickname is {{charName}}."],
            ["narrator-bubble", "Alright, {{charName}}, do you know what humans need most, in order to diminish their misery? Money. That’s right. And do you know where the most money lies in ‚Concrete Street‚?  In it’s ‚NIGHT FIGHTS‘! …"]
      ],
      monster: [
          ["narrator-bubble", "<h1>What the hell are YOU?</h1> My gosh, I've seen my share of ugly beasts here in 'Concrete Street', but I have to say, you do still stick out! What are you?"],
          ["you-bubble", "HUNGRY…!"],
          ["narrator-bubble", "Ugh … I meant, what kind of a being you are. Are you really as dumb as you look?"],
          ["you-bubble", "…?"],
          ["narrator-bubble", "… Well … How about a name? Do you at least know THAT?"],
          ["you-bubble", "<input class='dialog-input' placeholder='Name your fighter!' for='enter-name' stat='name'>"
           + "<button class='dialog-btn' onclick= \"Dialog.setCharData(this, 'name')\" name='enter-name'>That's my name!</button>"]
      ]
}